name: cricket application

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/**'
      - 'k8s/**'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: build application
      run: npm install 

    # application needs sql to run
  #  - name: run application
  #    run: node app.js

  docker:
    runs-on: ubuntu-latest
  #  needs: build

    steps: 
      - name: checkout code
        uses: actions/checkout@v4

      - name: install docker 
        uses: docker/setup-buildx-action@v1

      - name: login to docker
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}
      
      - name: docker push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/2-tier-app:${{github.run_id}}
      
